r"""Parse a Mermaid flowchart into a typed DFD inventory.

Stage 2 draws data flow diagrams in Mermaid. Mermaid has no native notion of "this
box is a data store and that one is a process", but the STRIDE skills need exactly
that: each letter analyzes only certain element types, so an untyped box cannot be
analyzed correctly.

The type comes from the node's **shape**, following classic DFD notation:

    Element          Notation             Mermaid       Example
    ---------------  -------------------  ------------  ----------------------
    External entity  rectangle            id[Name]      CUST[Customer]
    Process          circle / rounded     id(Name)      LOGIN(Login Handler)
    Data store       cylinder             id[(Name)]    USERS[(User Table)]
    Data flow        labelled arrow       a -->|l| b    CUST -->|creds| LOGIN
    Trust boundary   dashed region        subgraph      subgraph TB[...] ... end

Tolerated variants: `[/Name/]` and `[\Name\]` (parallelogram) also read as external
entities; `([Name])` and `((Name))` as processes; `{Name}` and `{{Name}}` as data
stores, though `[(Name)]` is preferred because a diamond means "decision" to anyone
reading the rendered diagram.

Because `[Name]` is also Mermaid's default shape, a diagram that ignores the
convention is all rectangles and therefore all external entities. That is silently
wrong rather than noisily wrong, so it gets its own warning.

Mermaid class tags (`:::name`, or a `class A,B name` statement) are still honoured as
an override where present, but they are not required and not the convention.

A node cannot carry a source location, so those ride in Mermaid comments, which render
as nothing and keep one artifact per diagram:

    %% file: LOGIN routes/login.ts
    %% file: USERS models/user.ts, models/session.ts

They come back on the `file_hints` key, mapping node id to a list of paths.

Standard library only.
"""

from __future__ import annotations

import re
from typing import Any

# Accepted class names per element type. Generous on synonyms because stage 2 is
# generated by a model, and rejecting `:::actor` would be pedantry.
CLASS_ALIASES: dict[str, str] = {
    "external": "external_entity",
    "external_entity": "external_entity",
    "externalentity": "external_entity",
    "entity": "external_entity",
    "actor": "external_entity",
    "user": "external_entity",
    "process": "process",
    "proc": "process",
    "handler": "process",
    "service": "process",
    "datastore": "data_store",
    "data_store": "data_store",
    "store": "data_store",
    "db": "data_store",
    "database": "data_store",
    "table": "data_store",
}

CANONICAL_SHAPE = {
    "external_entity": "[Name]",
    "process": "(Name)",
    "data_store": "[(Name)]",
}

# Optional trailing class tag on a node declaration.
_TAG = r"(?:\s*:::(?P<cls>[A-Za-z0-9_-]+))?"

# Order matters: the most specific bracket forms are tried first, or `[(User Table)]`
# is mis-read as a rectangle containing "(User Table".
_NODE_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("data_store", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\[\((?P<label>[^\]]+?)\)\]" + _TAG)),
    ("data_store", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\{\{(?P<label>[^}]+?)\}\}" + _TAG)),
    ("data_store", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\{(?P<label>[^}]+?)\}" + _TAG)),
    ("external_entity", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\[/(?P<label>[^\]]+?)/\]" + _TAG)),
    ("external_entity", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\[\\(?P<label>[^\]]+?)\\\]" + _TAG)),
    ("process", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\(\[(?P<label>[^\]]+?)\]\)" + _TAG)),
    ("process", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\(\((?P<label>[^)]+?)\)\)" + _TAG)),
    ("process", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\((?P<label>[^)]+?)\)" + _TAG)),
    ("external_entity", re.compile(r"(?<![A-Za-z0-9_])(?P<id>[A-Za-z0-9_][A-Za-z0-9_-]*)\[(?P<label>[^\]\[/(\\][^\]]*?)\]" + _TAG)),
)

_EDGE_RE = re.compile(
    r"(?P<src>[A-Za-z0-9_-]+)\s*"
    r"(?:-{2,}|-\.-|={2,})>?\s*"
    r"(?:\|(?P<label>[^|]*)\|)?\s*"
    r"(?P<dst>[A-Za-z0-9_-]+)"
)

# Source locations ride in Mermaid comments, since a node cannot carry one:
#   %% file: LOGIN routes/login.ts
#   %% file: USERS models/user.ts, models/session.ts
_HINT_RE = re.compile(r"^\s*%%\s*file:\s*(?P<id>[A-Za-z0-9_-]+)\s+(?P<paths>.+?)\s*$", re.I)

_CLASS_STMT_RE = re.compile(r"^\s*class\s+(?P<ids>[A-Za-z0-9_,\s-]+?)\s+(?P<cls>[A-Za-z0-9_-]+)\s*;?\s*$")
_SUBGRAPH_RE = re.compile(
    r"^\s*subgraph\s+(?:(?P<id>[A-Za-z0-9_-]+)\s*)?(?:\[(?P<bracket>[^\]]+)\]|(?P<bare>.+?))?\s*$"
)
_END_RE = re.compile(r"^\s*end\s*;?\s*$", re.I)
_SKIP_RE = re.compile(r"^\s*(flowchart|graph|classDef|style\s|linkStyle|direction|%%|click\s)", re.I)


def parse_mermaid(text: str) -> dict[str, Any]:
    """Extract a typed DFD inventory from a Mermaid flowchart.

    Returns the five element groups plus a `warnings` list. Never raises: a diagram
    it cannot read yields empty groups and warnings explaining why, which is more
    useful mid-run than an exception.
    """
    result: dict[str, Any] = {
        "external_entities": [],
        "processes": [],
        "data_stores": [],
        "data_flows": [],
        "trust_boundaries": [],
        "file_hints": {},
        "warnings": [],
    }
    if not text or not text.strip():
        result["warnings"].append("diagram is empty")
        return result

    nodes: dict[str, dict[str, Any]] = {}
    declared_classes: dict[str, str] = {}  # node id -> raw class name, from `class A,B name`
    boundary_stack: list[str] = []

    for raw_line in text.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            continue

        hint = _HINT_RE.match(line)
        if hint:
            paths = [p.strip() for p in re.split(r"[,\s]+", hint.group("paths")) if p.strip()]
            result["file_hints"].setdefault(hint.group("id"), []).extend(paths)
            continue

        if _END_RE.match(line):
            if boundary_stack:
                boundary_stack.pop()
            continue

        if line.lstrip().lower().startswith("subgraph"):
            subgraph = _SUBGRAPH_RE.match(line)
            title = "unnamed boundary"
            if subgraph:
                title = (subgraph.group("bracket") or subgraph.group("bare") or subgraph.group("id") or title).strip()
                title = title.strip('"')
            boundary_stack.append(title)
            if title not in result["trust_boundaries"]:
                result["trust_boundaries"].append(title)
            continue

        class_stmt = _CLASS_STMT_RE.match(line)
        if class_stmt:
            for node_id in re.split(r"[,\s]+", class_stmt.group("ids").strip()):
                if node_id:
                    declared_classes[node_id] = class_stmt.group("cls")
            continue

        if _SKIP_RE.match(line):
            continue

        # Node declarations. Blank each match so a looser later pattern cannot
        # re-read the same text.
        working = line
        for shape_type, pattern in _NODE_PATTERNS:
            for match in list(pattern.finditer(working)):
                node_id = match.group("id")
                if node_id in nodes:
                    continue
                nodes[node_id] = {
                    "name": match.group("label").strip().strip('"'),
                    "shape_type": shape_type,
                    "inline_class": match.group("cls"),
                    "trust_boundary": boundary_stack[-1] if boundary_stack else None,
                }
            working = pattern.sub(lambda m: " " * len(m.group(0)), working)

        for match in _EDGE_RE.finditer(line):
            result["data_flows"].append(
                {
                    "name": (match.group("label") or "").strip(),
                    "from": match.group("src"),
                    "to": match.group("dst"),
                    "trust_boundary": boundary_stack[-1] if boundary_stack else None,
                }
            )

    # Resolve each node's type: explicit tag wins, shape is the fallback.
    for node_id, node in nodes.items():
        raw_class = node["inline_class"] or declared_classes.get(node_id)
        tagged_type = CLASS_ALIASES.get(raw_class.lower()) if raw_class else None
        shape_type = node["shape_type"]

        if raw_class and not tagged_type:
            result["warnings"].append(
                f"node {node_id!r} carries an unrecognized class tag :::{raw_class}; using its shape instead"
            )

        if tagged_type:
            node["type"] = tagged_type
            if shape_type and shape_type != tagged_type:
                result["warnings"].append(
                    f"node {node_id!r} is drawn as a {shape_type.replace('_', ' ')} "
                    f"{CANONICAL_SHAPE[shape_type]} but tagged :::{raw_class}; trusting the tag. "
                    f"Redraw it as {CANONICAL_SHAPE[tagged_type]} so the picture matches the analysis."
                )
        else:
            node["type"] = shape_type

    # Map edge endpoints from node id to human name.
    for flow in result["data_flows"]:
        for end in ("from", "to"):
            node = nodes.get(flow[end])
            if node:
                flow[end] = node["name"]
            else:
                result["warnings"].append(
                    f"data flow references {flow[end]!r}, which is never declared with a shape"
                )
        if not flow["name"]:
            flow["name"] = f"{flow['from']} to {flow['to']}"

    group_for = {
        "external_entity": "external_entities",
        "process": "processes",
        "data_store": "data_stores",
    }
    for node_id, node in nodes.items():
        entry: dict[str, Any] = {"id": node_id, "name": node["name"]}
        if node.get("trust_boundary"):
            entry["trust_boundary"] = node["trust_boundary"]
        result[group_for[node["type"]]].append(entry)

    for hinted_id in result["file_hints"]:
        if hinted_id not in nodes:
            result["warnings"].append(
                f"'%% file: {hinted_id} ...' names a node that is never drawn; the hint is ignored"
            )

    if not nodes:
        result["warnings"].append(
            "no nodes recognized — check the shape convention: CUST[Customer] external entity, "
            "LOGIN(Login Handler) process, USERS[(User Table)] data store"
        )
    # `[Name]` is Mermaid's default shape, so a diagram that ignored the convention is
    # all rectangles and reads as all external entities. Silently wrong, so say so.
    if len(nodes) > 2 and all(n["type"] == "external_entity" for n in nodes.values()):
        result["warnings"].append(
            f"all {len(nodes)} nodes are plain rectangles, so every one reads as an external entity. "
            "That is almost certainly a diagram that did not follow the shape convention — processes "
            "should be (Name) and data stores [(Name)]. Five of the six STRIDE letters will return nothing."
        )
    if nodes and not result["external_entities"]:
        result["warnings"].append(
            "no external entities — Spoofing analyzes external entities and processes, so coverage may be thin"
        )
    if nodes and not result["processes"]:
        result["warnings"].append(
            "no processes — Elevation of Privilege analyzes processes only and will return nothing"
        )

    return result


def render_inventory(parsed: dict[str, Any]) -> str:
    """Render the parsed inventory as the element list the skills iterate."""
    lines: list[str] = []
    groups = (
        ("External entities", "external_entities"),
        ("Processes", "processes"),
        ("Data stores", "data_stores"),
        ("Data flows", "data_flows"),
    )
    for label, key in groups:
        items = parsed.get(key) or []
        if not items:
            continue
        lines.append(f"{label}:")
        for item in items:
            detail = []
            if item.get("from") and item.get("to"):
                detail.append(f"{item['from']} -> {item['to']}")
            if item.get("trust_boundary"):
                detail.append(f"inside {item['trust_boundary']}")
            if item.get("file_hints"):
                detail.append("implemented in " + ", ".join(item["file_hints"]))
            if item.get("description"):
                detail.append(item["description"])
            lines.append(f"  - {item['name']}" + (f" ({'; '.join(detail)})" if detail else ""))
        lines.append("")

    if parsed.get("trust_boundaries"):
        lines.append("Trust boundaries:")
        lines.extend(f"  - {b}" for b in parsed["trust_boundaries"])
        lines.append("")

    return "\n".join(lines).strip()
